### ISSUE TITLE
Fix saving a study with no title & empty question

### ISSUE THREAD

**Issue by srzvan** [Thinslices/skill-development#15]
### **Context**
Currently, the app lets you save a study without a title & with an empty question.

### **Expected outcome**
The user **should not be able** to save an "empty" study.

### Scenarios
**Given** the user is on the edit study page
**And** the study has
- a title
- a variable number of questions with title & answer
- an empty question

**When** the user publishes or saves as draft the current study
**Then** the update to the study should not contain the empty question

---

**Given** the user is on the edit study page
**And** the study has
- a title
- one or more questions that have only title

**When** the user publishes or saves as draft the current study
**Then** the update to the study should contain the question(s) that have only titles

Note: keep in mind that we need to edit/change the logic in the React about the index value.

**Comment by razvan-thinslices** [comment]
@srzvan #2 would be addressed in this issue and we can close it as won't fix. Right?

**Comment by srzvan** [comment]
@razvan-thinslices, I believe so.
