### ISSUE TITLE
Fix delete study

### ISSUE THREAD

**Issue by srzvan** [Thinslices/skill-development#16]
**Context**
When clicking the _Delete_ button from the _My studies_ view the user is prompted to confirm his choice **only after** clicking the _Add study_ button

The delete study functionality is present in 2 views:
* studies - where all the studies are visible
  * **Important note**: users with a role of admin can choose to delete any study, regardless of owner
* my studies - the current user can choose to delete any of their studies

**Expected outcome**
Clicking the _Delete_ button should prompt the user to confirm his choice in the current view.

**Comment by galer7** [comment]
It's not clear to me if you are asking for a prompt to show before the delete operation occurs, or if there is a weird bug regarding the order of _Delete_ and _Add study_ executions.

If it is the latter, I could not reproduce it.
